<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1bbe730862375edf05e32555faaad742
{
    public static $prefixLengthsPsr4 = array (
        'Z' => 
        array (
            'ZipMerge\\' => 9,
        ),
        'P' => 
        array (
            'PHPZip\\Zip\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ZipMerge\\' => 
        array (
            0 => __DIR__ . '/..' . '/grandt/phpzipmerge/src/ZipMerge',
        ),
        'PHPZip\\Zip\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpzip/phpzip/src/Zip',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'RelativePath' => __DIR__ . '/..' . '/grandt/relativepath/RelativePath.php',
        'com\\grandt\\BinString' => __DIR__ . '/..' . '/grandt/binstring/BinString.php',
        'com\\grandt\\BinStringStatic' => __DIR__ . '/..' . '/grandt/binstring/BinStringStatic.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1bbe730862375edf05e32555faaad742::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1bbe730862375edf05e32555faaad742::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1bbe730862375edf05e32555faaad742::$classMap;

        }, null, ClassLoader::class);
    }
}
